**Numpy:Package for Multidimensional array**

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)

In [4]:
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [7]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [11]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.arange(46,1,-5)

array([46, 41, 36, 31, 26, 21, 16, 11,  6])

In [15]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
##create an array of 2 rows and 10 coloumns

In [17]:
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.random.rand(3,2)

array([[0.60808147, 0.15935875],
       [0.49542182, 0.7225663 ],
       [0.07722855, 0.37305343]])

In [22]:
np.random.randn(3,2)

array([[ 0.17446281,  0.68373438],
       [ 0.72216879, -1.2365694 ],
       [ 0.77898992, -0.52366697]])

In [23]:
np.random.randint(1,5)

3

In [24]:
np.random.randint(34,100,50)

array([72, 50, 86, 88, 93, 78, 37, 68, 97, 99, 41, 57, 46, 79, 90, 83, 57,
       62, 93, 82, 66, 54, 94, 85, 55, 61, 97, 68, 82, 87, 94, 57, 91, 81,
       95, 61, 90, 89, 49, 63, 52, 71, 64, 83, 61, 87, 47, 84, 37, 37])

In [25]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
rand_array=np.random.randint(0,100,20)
rand_array

array([50, 22, 42, 46, 44, 64,  0, 62, 80, 30, 27, 87, 92, 89, 56, 11, 71,
       54, 64, 19])

In [27]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [28]:
rand_array.min()

0

In [29]:
rand_array.argmin()

6

In [30]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
a=np.random.rand(2,3)
a

array([[0.73576023, 0.20504466, 0.11643775],
       [0.12357864, 0.69517793, 0.41205354]])

In [36]:
a.T

array([[0.73576023, 0.12357864],
       [0.20504466, 0.69517793],
       [0.11643775, 0.41205354]])

In [32]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
sample_array[3]

13

In [34]:
sample_array[3:7]

array([13, 14, 15, 16])

In [37]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [39]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [41]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [42]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [44]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

**Two-Dimesional Array**

In [45]:
import numpy as np

In [48]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [49]:
sample_matrix[0:2,2]

array([ 1, 21])

In [50]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [51]:
sample_matrix[2]

array([56, 76, 24,  7])

In [53]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [54]:
sample_matrix[:,3]

array([23, 33,  7])

In [55]:
sample_matrix[(0,2),:]

array([[50, 20,  1, 23],
       [56, 76, 24,  7]])

In [56]:
sample_matrix[2,0:2]

array([56, 76])

In [57]:
sample_matrix[:,2]

array([ 1, 21, 24])

In [58]:
sample_array=np.arange(1,20)

In [60]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [61]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [62]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [63]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [64]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [66]:
np.max(sample_array)

19

In [67]:
np.min(sample_array)

1

In [69]:
np.argmax(sample_array)

18

In [70]:
np.argmin(sample_array)

0

In [65]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [71]:
np.std(sample_array)

5.477225575051661

In [72]:
np.var(sample_array)

30.0

In [73]:
np.mean(sample_array)

10.0

In [74]:
array=np.random.randn(3,4)
array

array([[ 1.70072406, -0.90556162,  1.47039898,  0.7900654 ],
       [ 1.45952055,  0.47677651,  0.03476286, -0.31553303],
       [ 0.4488988 , -0.98314035, -0.1689882 ,  1.07556579]])

In [75]:
np.round(array,decimals=3)

array([[ 1.701, -0.906,  1.47 ,  0.79 ],
       [ 1.46 ,  0.477,  0.035, -0.316],
       [ 0.449, -0.983, -0.169,  1.076]])

In [76]:
sports=np.array(['golf','cricket','fball','cricket','fball','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')